name: Build and publish package
on:
  push:
    branches:
      - main

jobs:
  build-graphviz-linux64:
    name: Build GraphViz for Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: daaku/gh-action-apt-install@v4
        with:
          packages: swig
      - name: Build GraphViz library 
        run: ./build-graphviz.sh
      - uses: actions/upload-artifact@v4
        with:
          name: graphviz-linux-x64
          path: dist
  build-graphviz-win64:
    name: Build GraphViz for Windows x64
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Remove Strawberry
        run: rm -r C:/Strawberry
      - name: Build GraphViz library
        run: .\BuildGraphviz.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: graphviz-windows-x64
          path: dist
  
  publish-package:
    name: Build and publishes NuGet package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Download built platform binaries
        uses: actions/download-artifact@v4
        with:
          path: GraphVizard.Interop
          pattern: graphviz-*
      - run: dotnet pack -o pkg
      - uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: pkg
      - env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push pkg/GraphVizard.Interop*.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
