name: Build and publish package
on:
  push: 
    tags:
      - "*"

jobs:
  build-graphviz-linux64:
    name: Build GraphViz for Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: daaku/gh-action-apt-install@v4
        with:
          packages: swig
      - name: Build GraphViz library 
        run: build-graphviz.sh
      - uses: actions/upload-artifact@v4
        with:
          name: graphviz-linux-x64
          path: dist
